name: Build and publish backend and frontend images to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ARGO_TOKEN }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      ##################
      # Backend
      ##################
      - name: Build & push backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile.backend
          push: true
          tags: |
            ghcr.io/morph2k/backend:latest
            ghcr.io/morph2k/backend:${{ github.sha }}

      ##################
      # Frontend
      ##################
      - name: Build & push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile.frontend
          push: true
          tags: |
            ghcr.io/morph2k/frontend:latest
            ghcr.io/morph2k/frontend:${{ github.sha }}
